steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/enterprisedemos-258322/bookshelf', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/enterprisedemos-248322/bookshelf"]
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - filename='bookshelf-frontend.yaml'
  - --image=gcr.io/enterprisedemos-258322/bookshelf:latest
  - --location=us-central1-a
  - --cluster=democluster
